### ISSUE TITLE
error when starting ./start.sh

### ISSUE THREAD

**Issue by zablah** [devalexanderdaza/yowsapp-framework#11]
I'm working on ubuntu 18.04 server 
```
yowsup-cli version
yowsup-cli v3.2.0
Using yowsup v3.2.3

```

```
./start.sh 
[Whatsapp] Mac started

[Whatsapp] El layer estado es: org.openwhatsapp.yowsup.event.network.connect
E 2019-05-14 21:40:28,961 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.6/asyncore.py", line 441, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.6/asyncore.py", line 429, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  [Previous line repeated 3 more times]
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/noise/layer.py", line 63, in on_auth
    assert type(local_static) is KeyPair
AssertionError
```

**Comment by x-frst** [comment]
same error

**Comment by devalexanderdaza** [comment]
Hi! This error has defined in https://github.com/tgalal/yowsup/milestone/2 with the name **_Asyncore Error_** Awaiting the response from the creator.

**Comment by devalexanderdaza** [comment]
Solve issue in [this commit](https://github.com/tgalal/yowsup/commit/3ef39cc6bb631222e0f4ca2cc18c5f14757778ed)
