### ISSUE TITLE
Error when running ./start.sh

### ISSUE THREAD

**Issue by x-frst** [devalexanderdaza/yowsapp-framework#17]
I'm running on latest yowsapp-framework & latest yowsup! Getting following error after just executing ./start.sh

```
->>>>>> MESSAGE RECEIVED!!!!!!
->>>>>> TEXT MESSAGE RECEIVED!!!!!!
E 2019-05-30 10:37:56,528 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
 File "/usr/lib/python3.6/asyncore.py", line 83, in read
   obj.handle_read_event()
 File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
   self.handle_read()
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 48, in handle_read
   self.connectionCallbacks.onRecvData(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/layer.py", line 100, in onRecvData
   self.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/network/layer.py", line 103, in receive
   self.toUpper(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/noise/layer_noise_segments.py", line 39, in receive
   self.toUpper(bytes(data))
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/noise/layer.py", line 156, in receive
   self._flush_incoming_buffer()
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
   self.toUpper(self._wa_noiseprotocol.receive())
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/coder/layer.py", line 21, in receive
   self.toUpper(node)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
   self.toUpper(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_control.py", line 35, in receive
   self.toUpper(protocolTreeNode)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 194, in receive
   s.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 31, in receive
   self.onMessage(protocolTreeNode)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 63, in onMessage
   self.handleEncMessage(protocolTreeNode)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 75, in handleEncMessage
   self.handlePreKeyWhisperMessage(node)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/axolotl/layer_receive.py", line 120, in handlePreKeyWhisperMessage
   self.toUpper(node)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 194, in receive
   s.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 130, in receive
   recv(node)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/protocol_messages/layer.py", line 23, in recvMessageStanza
   self.toUpper(TextMessageProtocolEntity.fromProtocolTreeNode(node))
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
   self.__upper.receive(data)
 File "/usr/local/lib/python3.6/dist-packages/yowsup/layers/interface/interface.py", line 80, in receive
   self.entity_callbacks[entityType](entity)
 File "/home/ubuntu/Desktop/yowsapp-framework/app/layer.py", line 70, in on_message
   self.onTextMessage(message_entity)
 File "/home/ubuntu/Desktop/yowsapp-framework/app/layer.py", line 89, in onTextMessage
   message = Message(messageProtocolEntity)
 File "/home/ubuntu/Desktop/yowsapp-framework/app/models/message.py", line 19, in __init__
   self.build()
 File "/home/ubuntu/Desktop/yowsapp-framework/app/models/message.py", line 23, in build
   self.build_text_message()
 File "/home/ubuntu/Desktop/yowsapp-framework/app/models/message.py", line 35, in build_text_message
   self.put_command()
 File "/home/ubuntu/Desktop/yowsapp-framework/app/models/message.py", line 64, in put_command
   self.command = helper.command(self.message_entity)
 File "/home/ubuntu/Desktop/yowsapp-framework/app/utils/helper.py", line 161, in command
   command = message(message_entity).split(' ', 1)[0]
 File "/home/ubuntu/Desktop/yowsapp-framework/app/utils/helper.py", line 123, in message
   if is_command(message):
 File "/home/ubuntu/Desktop/yowsapp-framework/app/utils/helper.py", line 143, in is_command
   macShorcut = message[:1]
TypeError: 'TextMessageProtocolEntity' object is not subscriptable
```

**Comment by VPeeters** [comment]
In app/utils/helper.py, replace:
```python
def message(message):
    # message = clean_message(message)
    if is_command(message):
        return message[1:]
    else:
        return message
```

by:

```python
def message(message):
    # message = clean_message(message)
    message = message.conversation
    if is_command(message):
        return message[1:]
    else:
        return message
```

This is a quick & dirty fix, but it works for now.

**Comment by x-frst** [comment]
@VPeeters thanks this worked I can able to receive message but in strange way I mean when I'm sending `!hi` it is sending me `Mensaje recibido: !hi` like it is repeating my message instead of sending actual module reply!

**Comment by VPeeters** [comment]
@AmitGamingKing correct me if I'm wrong, but isn't that normal behavior from the hihelp module? (I personally disabled that module. My own modules work as expected)

**Comment by x-frst** [comment]
Yes sorry I just checked hihelp module and it's changed, I mean the reply specified is different, previously I was using daniel repo so it was different in that!

**Comment by x-frst** [comment]
@devalexanderdaza I don't know it is possible or not but how to receive multimedia message? I'm getting error, I'm not sure if you implemented this or not, but if yes then please tell me why I'm getting error?

**Comment by devalexanderdaza** [comment]
> @devalexanderdaza I don't know it is possible or not but how to receive multimedia message? I'm getting error, I'm not sure if you implemented this or not, but if yes then please tell me why I'm getting error?

Currently there is an error in the validation of multimedia messages that I hope to solve this week as soon as I have a time.

**Comment by devalexanderdaza** [comment]
Solved on [21](https://github.com/devalexanderdaza/yowsapp-framework/pull/21)
