### ISSUE TITLE
Cant Register

### ISSUE THREAD

**Issue by fernac03** [devalexanderdaza/yowsapp-framework#18]
Enter your country code: 55
Enter your mobile number without country code and + and 00: 3199XXXXXXX
Enter your MCC code <Lis of all MCC codes: https://www.mcc-mnc.com/>: 724
Enter your MNC code <Lis of all MCC codes: https://www.mcc-mnc.com/>: 12
Insert option number for code validation: 1. SMS - 2. VOICE: 1
E 2019-05-30 16:32:41,046 yowsup.config.manager - Could not find a config for username=553199XXXXXXX, paths checked: /root/.config/yowsup/553199XXXXXXX/config.json:/root/.config/yowsup/553199XXXXXXX/config.yo
Traceback (most recent call last):
 File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 350, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/usr/local/bin/yowsup-cli", line 359, in handleRequestCode
    from yowsup.registration import WACodeRequest
  File "/usr/local/lib/python2.7/site-packages/yowsup/registration/__init__.py", line 1, in <module>
    from .coderequest import WACodeRequest
  File "/usr/local/lib/python2.7/site-packages/yowsup/registration/coderequest.py", line 1, in <module>
    from yowsup.common.http.warequest import WARequest
  File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/__init__.py", line 2, in <module>
    from .warequest import WARequest
  File "/usr/local/lib/python2.7/site-packages/yowsup/common/http/warequest.py", line 10, in <module>
    from yowsup.axolotl.factory import AxolotlManagerFactory
  File "/usr/local/lib/python2.7/site-packages/yowsup/axolotl/factory.py", line 1, in <module>
    from yowsup.axolotl.manager import AxolotlManager
  File "/usr/local/lib/python2.7/site-packages/yowsup/axolotl/manager.py", line 19, in <module>
    from yowsup.axolotl.store.sqlite.liteaxolotlstore import LiteAxolotlStore
  File "/usr/local/lib/python2.7/site-packages/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 6, in <module>
    from .litesenderkeystore import LiteSenderKeyStore
  File "/usr/local/lib/python2.7/site-packages/yowsup/axolotl/store/sqlite/litesenderkeystore.py", line 3, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by x-frst** [comment]
It clearly says that you haven't installed the sqlite3 module, I want to ask on which Python version are you running this? `sudo apt-get install libsqlite3-dev` this may fix your problem.

**Comment by fernac03** [comment]
after install libsqlite3-dev 
i try with  python2.7 , python3 , pyhton3.5 and python3.6  all is tha same 
File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 325, in process
    super(RegistrationArgParser, self).process()
  File "/usr/local/bin/yowsup-cli", line 206, in process
    self._config = self._config_manager.load(config_phone)
  File "/usr/local/lib/python3.6/site-packages/yowsup/config/manager.py", line 52, in load
    return self.load_path(fpath)
  File "/usr/local/lib/python3.6/site-packages/yowsup/config/manager.py", line 84, in load_path
    datadict = self.TYPES[configtype]().reverse(data)
  File "/usr/local/lib/python3.6/site-packages/yowsup/config/transforms/dict_json.py", line 10, in reverse
    return json.loads(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

**Comment by devalexanderdaza** [comment]
@fernac03 Type on your console `yowsup-cli version` and paste output

**Comment by fernac03** [comment]
@devalexanderdaza 

yowsup-cli v3.2.0
Using yowsup v3.2.3
