### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by alikhil** [devalexanderdaza/yowsapp-framework#34]
When I run `yowsapp_installer.sh` is clean ubuntu 16.04 I got the following error:

```
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 679, in <module>
    if not parser.process():
  File "/usr/local/bin/yowsup-cli", line 352, in process
    self.handleRegister(self.args["register"], config)
  File "/usr/local/bin/yowsup-cli", line 378, in handleRegister
    req = WARegRequest(config, code)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/registration/regrequest.py", line 35, in __init__
    super(WARegRequest,self).__init__(config)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/common/http/warequest.py", line 62, in __init__
    .get_manager(self._config.phone)  # type: yowsup.axolotl.manager.Axolotlmanager
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/factory.py", line 15, in get_manager
    store = LiteAxolotlStore(dbpath)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 15, in __init__
    self.identityKeyStore = LiteIdentityKeyStore(conn)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/axolotl/store/sqlite/liteidentitykeystore.py", line 22, in __init__
    registration_id = KeyHelper.generateRegistrationId(True)
TypeError: generateRegistrationId() takes 0 positional arguments but 1 was given
```

Maybe dockerization will help to achieve the same enviroment? Could you please make a Dockerfile for the project?

**Comment by devalexanderdaza** [comment]
There are still many things to be repaired and to integrate and they are my priority and the priority of the community that is growing around Yowsapp, however, I will keep it in mind for its correct deployment in Docker

Regarding the error that occurs, could you please share the version and configuration of the Yowsupp that you have installed on your machine? You can achieve it with:

`$> yowsup-cli version`
